# Generated by Django 5.0.6 on 2024-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_profile', '0003_alter_photo_introduce_alter_photo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='introduce',
            field=models.FileField(upload_to='introduce/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user_image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
