# Generated by Django 5.0.6 on 2024-07-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
